% This is a simple script to filter the periapsis map data chunks
% generated by 'periapsis_map_parasim.m'
clear; clc; close('all')

for k = 1:1:8 % For each chunk corresponding to a Sun angle epoch
    % Load that datasetcompose('saved data/generated/periapsis_maps/result_chunks/%d/', dv)
    filename = compose('saved data/generated/periapsis_maps/result_chunks/100/1_100_%d.mat', k);
    load(filename{1})

    for q = 1:1:length(chunk.sim_res) % For each simulation
        % Which simulations swung below 350 km altitude?
        LEO_idx = vecnorm(chunk.sim_res(q).periy(1:3, :) + [0.0122; 0; 0], 2) < 0.0175;

        if ~isempty(chunk.sim_res(q).perix(LEO_idx))  % If some sims swung below this altitude and into LEO
            % Compose the altitude and time-before-epoch of this
            % periapsis into a vector for Commadn Window output
            [chunk.sim_res(q).perix(LEO_idx); ...
                vecnorm(chunk.sim_res(q).periy(1:3, LEO_idx) + [0.0122; 0; 0], 2) * 384400 - 6378]

            % For periapsis that happen within ~7 months of epoch 
            if min(chunk.sim_res(q).perix(LEO_idx)) > -50

                % Create a breakpoint opportunity for very close approaches
                if max(vecnorm(chunk.sim_res(q).periy(1:3, LEO_idx) + [0.0122; 0; 0], 2) * 384400 - 6378) > 100
                    x = 1;  % Dummy line of code
                end
            end
        end
    end
end