%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This script demonstrates two things:
%   1)  It demonstrates a 'commensur-ating' process applied to the
%       Sun-Earth-Moon dynamics.  This process yields a slightly different
%       lunar orbit, for which the dynamics of the Earth, Moon and Sun repeat
%       at a predictable cycle.  This cycle occurs every three sidereal years,
%       or 40x modified sidereal months.  Using this choice of modified orbit,
%       the script demonstrates the difference between the 'true' dynamics and
%       the 'commensurate-d' dynamics over one synodic period of a chosen orbit
%   2)  The script finds a L4 SPO synodic period, for which this hypothetical
%       SPO is periodic in the CR3BP at some multiple of three sidereal
%       years.  Specifically, there is an SPO that repeats every 9
%       sidereal years geometrically quite close to the SPO generated by the
%       'SPO1' initial condition used in the collaboration.  It is this
%       hypothetical SPO that can be continued into a periodic orbit in the
%       'commensurate-d' dynamics
%
% Author:  Andrew Binder (2024)
%
% Inputs: None
% Outputs: None
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% MATLAB Initialization and MATLAB Constants Definition
clear;
clc;
close('all');

addpath(genpath('..\utilities')); % Add folder and subfolders
addpath(genpath('..\saved data')); % Add folder and subfolders

%% Constants of the Problem
mu_moon = 4902.8005821478; % All in km^3 / s^2
mu_earth = 398600.4415;
mu_sun = 132712440018;

aE_dim = 149598023; % Earth's SMA about the Sun

mu = mu_moon / (mu_earth + mu_moon); % mu value for the Earth-Moon system
mu_oom = round(log10(mu));
mu_SF_known = 8; % We know 8 Earth sigfigs, 9 Moon sigfigs

% mu rounded to appropriate significance
mu = round(mu*10^(mu_SF_known - mu_oom - 1)) / 10^(mu_SF_known - mu_oom - 1);

muS = mu_sun / (mu_earth + mu_moon); % Sun's n.d. SGP [L^3 / T^2]

% Commensurable char. length has a t* that is best rational approx. to a tol.
N = 3;
D = 40;

% Approximately equal to the average SMA of the Moon about EM Bary
l_star = ((N / D)^2 / (muS + 1))^(1 / 3) * aE_dim;

% l_star = 384400;  % Equal to the average SMA of the Moon about EM Bary
t_star = sqrt(l_star^3/(mu_moon + mu_earth)); % Div. by 86400 > time in days
v_star = l_star / t_star; % Characteristic speed, in km/s

aE = aE_dim / l_star;  % Nondimensionalize the Earth-Sun distance

% Lunar orientation relative to ecliptic inertial frame at epoch
M0 = 0;
inc = deg2rad(5.145);
RAAN = 0;

%% Definition of option structures
opts = odeset("RelTol", 1e-12, "AbsTol", 1e-12);

%% Propagate a sample reference trajectory in the BCIR4BP

% Load in L4 SPOs for demonstration of commensurated dynamics
load('..\saved data\generated\l4_short_period.mat')

% Find the Q value such that 2 * pi * D / Q is as close as possible to
% the period of 'SPO1' ~= index #44 of my dataset
Q_mult = 3;
Q = round(Q_mult/(l4_short_period(44).TIP / 2 / pi / D));

% An SPO with this synodic period repeats about every nine sidereal years
TIP_commens = 2 * pi * (Q_mult * D) / Q

% M(\tau), B(\tau), and the chosen PO all repeat at this nondimensional period
T_repeat_nd = 2 * pi * D * Q_mult % Equals 240\pi

% Repitition period of the system + SPO dynamics, but now dimensionalized
T_repeat_days = T_repeat_nd * t_star / 86400

% 'SPO1' from the email has the following IC:
% IC_SPO1 = [4.8784941344943100E-1;
%            1.0739139120852199E+0;
%            -4.7806160811468755E-24;
%            3.1656188631046445E-1;
%            -1.3909971587341163E-1;
%            8.4064917839784221E-25]
%
% Which lies somewhere between entry #44 and #45 in my saved
% 'l4_short_period' dataset.  An SPO with the period described above
% lies somewhere between entry #47 and #48 in my saved dataset.

% Choose the commensurate orbit's proxy sample from the dataset
orbit = l4_short_period(48);
IC = orbit.ic;

% With sigma = 0, this simulates the CR3BP
ode_func = @(t, y) bcir4bp_stm(t, y, ...
                               earth_moon_massparam = mu, ...
                               sun_sgp_nondim = muS, ...
                               sun_effect_slider = 0.0, ...
                               moon_arglat_at_epoch = M0, ...
                               moon_inclination = inc, ...
                               moon_right_ascension = RAAN, ...
                               earth_sma_nondim = aE, ...
                               stm_enabled = false);

cr3bp_ss = ode45(ode_func, [0, orbit.TIP], IC, opts);

% Visualize the CR3BP's propogation of our proxy's IC
figure(1);

hold on;
axis equal;
grid on;

plot3(cr3bp_ss.y(1, :), cr3bp_ss.y(2, :), cr3bp_ss.y(3, :), ...
      'Color', 'black', 'LineWidth', 2)

%% Plot one rev of the IC with the commensurate value for the Moon's SMA
% Set the Sun's effect to full-strength for this sim and the next
ode_func = @(t, y) bcir4bp_stm(t, y, ...
                               earth_moon_massparam = mu, ...
                               sun_sgp_nondim = muS, ...
                               sun_effect_slider = 1.0, ...
                               moon_arglat_at_epoch = M0, ...
                               moon_inclination = inc, ...
                               moon_right_ascension = RAAN, ...
                               earth_sma_nondim = aE, ...
                               stm_enabled = false);

bcir_ss = ode45(ode_func, [0, orbit.TIP], IC, opts);

% Visualize the BCIR4BP's propogation of our proxy's IC, and mark its initial
% condition and its final condition
plot3(bcir_ss.y(1, :), bcir_ss.y(2, :), bcir_ss.y(3, :), 'b')
scatter3(bcir_ss.y(1, end), bcir_ss.y(2, end), bcir_ss.y(3, end), 'rs')

%% Plot one rev of the IC with the true value for the Moon's SMA
% Modify characteristic quantities to match real average values
l_star = 384400; % Also equal to the average SMA of the Moon about EM Bary
t_star = sqrt(l_star^3/(mu_moon + mu_earth)); % Div. by 86400 > time in days
v_star = l_star / t_star; % Characteristic speed, in km/s

aE = aE_dim / l_star;

ode_func = @(t, y) bcir4bp_stm(t, y, ...
                               earth_moon_massparam = mu, ...
                               sun_sgp_nondim = muS, ...
                               sun_effect_slider = 1.0, ...
                               moon_arglat_at_epoch = M0, ...
                               moon_inclination = inc, ...
                               moon_right_ascension = RAAN, ...
                               earth_sma_nondim = aE, ...
                               stm_enabled = false);

bcir_ss = ode45(ode_func, [0, orbit.TIP], IC, opts);

% Plot the trajectory and its final condition (two traj share IC)
plot3(bcir_ss.y(1, :), bcir_ss.y(2, :), bcir_ss.y(3, :), 'r')
scatter3(bcir_ss.y(1, end), bcir_ss.y(2, end), bcir_ss.y(3, end), 'bs')
scatter3(bcir_ss.y(1, 1), bcir_ss.y(2, 1), bcir_ss.y(3, 1), 'r')

xlabel("x-distance from EM barycenter [nd]")
ylabel("y-distance from EM barycenter [nd]")
zlabel("z-distance from EM barycenter [nd]")

legend("SPO in the CR3BP", ...
       "Prop. of IC with commens. Moon SMA", "", ...
       "Prop. of IC with typical Moon SMA", "", ...
       "Initial State", "Location", "best")

title("Closeness of 'Commensurate-d' Dynamics")